stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/dataset.csv
    - src/preprocess.py
    outs:
    - data/processed.csv
  train:
    cmd: python src/train.py
    deps:
    - data/processed.csv
    - src/train.py
    params:
    - model
    - train
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed.csv
    - models/model.pkl
    - src/evaluate.py
    metrics:
    - metrics/metrics.json:
        cache: false
